---
name: Workflow Main
on: 
  workflow_call:
    secrets:
      ACCOUNT_ID:
        required: true
      AWS_REGION:
        required: true
      ECR_PROJ_NAME:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      TF_LOG:
        required: true
      IMAGE_TAG:
        required: false

jobs:
    
  ContinuousIntegration:
    uses: ./.github/workflows/pylint_and_pytest.yaml
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      IMAGE_TAG: ${{ secrets.IMAGE_TAG || 'latest' }}

  ContinuousDelivery:
    uses: ./.github/workflows/bp_base.yaml
    secrets:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_PROJ_NAME: ${{ secrets.ECR_PROJ_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: [ContinuousIntegration]

  ContinuousDeployment:
    uses:  ./.github/workflows/terraform.yaml
    secrets:
      TF_LOG: ${{ secrets.ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: [ContinuousDelivery]
