---
name: Lint and BP (EC2 and Lambda)
on: 
  workflow_call:
    secrets:
      ACCOUNT_ID:
        required: true
      AWS_REGION:
        required: true
      ECR_LAMBDA_NAME:
        required: true
      ECR_EC2_NAME:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
    
  ContinuousIntegration:
    uses: ./.github/workflows/pylint_and_pytest.yaml

  BuildAndPush:
    uses: ./.github/workflows/bp_lambda_ec2.yaml
    secrets:
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_LAMBDA_NAME: ${{ secrets.ECR_LAMBDA_NAME }}
      ECR_EC2_NAME: ${{ secrets.ECR_EC2_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: [ContinuousIntegration]
