name: Lint and Test Validations
on: 
  workflow_call:
    secrets:
      AWS_REGION:
        required: false
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  setup-build-deploy:
    name: Lint and Test Validations
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:

      - uses: actions/checkout@v4
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4

      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |-
          pip install -r requirements.txt

      - name: Lint
        run: |- 
          pylint .

      - name: Test
        run: |-
          pytest .
        continue-on-error: false
