name: Lint and Test Validations
on: [workflow_call]

jobs:
  setup-build-deploy:
    name: Lint and Test Validations
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:

      - uses: actions/checkout@v4
      - name: Set up Python 3.10.4
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4

      # - name: Checkout the repository to the runner
      #   uses: actions/checkout@v2

      - name: Install Dependencies
        run: |-
          pip install -r requirements.txt

      - name: Lint
        run: |- 
          pylint --disable C0103 .

      - name: Test
        run: |-
          pytest .
        continue-on-error: true
