---
name: Workflow Main
on: 
  workflow_call:
    secrets:
      ACCOUNT_ID:
        required: true
      AWS_REGION:
        required: true
      LAMBDA_NAME:
        required: true
      EC2_NAME:
        required: true
      TF_LOG:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:

  ContinuousIntegration:
    steps:

      - name: Checkout the repository to the runner
        uses: actions/checkout@v2
    
      - name: Run CI
        uses: ./.github/workflows/pylint_and_pytest.yaml

  # BuildAndPush:
  #   uses: ./.github/workflows/lambda_and_ec2.yaml
  #   secrets:
  #     ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  #     AWS_REGION: ${{ secrets.AWS_REGION }}
  #     LAMBDA_NAME: ${{ secrets.LAMBDA_NAME }}
  #     EC2_NAME: ${{ secrets.EC2_NAME }}
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #   needs: [ContinuousIntegration]

  # Terraform:
  #   uses: ./.github/workflows/review_and_apply.yaml
  #   secrets:
  #     TF_LOG: ${{ secrets.TF_LOG }}
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #   needs: [BuildAndPush]

